# /docker-compose.yml (VERSIÓN CORREGIDA Y FINAL)

version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ./app:/code/app  # Mapea el código para el desarrollo con --reload
      - docs_source:/docs_source
      - docs_build:/docs_build
    environment:
      # AHORA LEE TODAS LAS VARIABLES DESDE EL ARCHIVO .env
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # AHORA LEE LAS CREDENCIALES DESDE EL ARCHIVO .env
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - docs_build:/var/www/html
    depends_on:
      - app

volumes:
  docs_source:
  docs_build:
  postgres_data: