# /docker-compose.yml
services:
  # Servicio de la aplicación de edición FastAPI
  app:
    build: ./app # Construye la imagen desde la carpeta 'app'
    expose:
      - "8000" # Expone el puerto solo a otros servicios del compose (Nginx)
    volumes:
      # Volumen para los archivos Markdown (fuente de verdad)
      - docs_source:/docs_source
      # Volumen donde MkDocs construirá el sitio HTML
      - docs_build:/docs_build
    # El comando se mantiene igual, pero lo ponemos en el Dockerfile de la app
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Servicio del Reverse Proxy Nginx
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80" # Expone el puerto 80 de Nginx al puerto 8080 de tu máquina
    volumes:
      # Monta nuestro archivo de configuración personalizado
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Monta el volumen del sitio construido para que Nginx pueda servirlo
      - docs_build:/var/www/html
    depends_on:
      - app # Nginx no iniciará hasta que la app esté lista

volumes:
  docs_source:
  docs_build:
